Импортирую библиотеку NumPy с общепринятым сокращением

In [160]:
import numpy as np

Создание массивов из обычных списков

Теперь создаю одномерный массив (вектор) и присваиваю его переменной

In [161]:
arr_vector = np.array([1, 1, 2, 3, 5, 8, 13])
type(arr_vector)

numpy.ndarray

Теперь создаю двумерный массив (матрицу) и присваиваю переменной

In [162]:
arr_matrix = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
arr_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Создание массивов с помощью специальных функций zeros, ones и arange, а также eye и empty

Создаю матрицу, заполненную нулями, с помощью функции numpy.zeros(...)

In [163]:
arr_matrix_zeros = np.zeros((3, 4))
arr_matrix_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Создаю тензор третьего ранга, ну или параллелепипед, заполненный единицами, с помощью функции numpy.ones(...)

In [164]:
tensor_3d = np.ones((2, 3, 4))
tensor_3d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Функция numpy.arange() может принимать 1, 2 или 3 параметра:
    1. При одном параметре (числе) функция создаст массив с последовательностью от 0 включительно до этого числа не включительно с шагом 1
    2. При двух параметрах функция создаст массив от первого числа включительно до второго не включительно с шагом 1
    3. При трех параметрах функция создаст массив от первого числа включительно до второго не включительно с шагом, указанным числом в третьем параметре

Теперь создам последовательность чисел от 1 до 6 с шагом 0.5 с помощью функции numpy.arange(начало, конец, шаг)

In [165]:
arr_sequence = np.arange(1, 6, 0.5)
print(arr_sequence)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5]


In [166]:
type(arr_sequence)

numpy.ndarray

Также можно создавать последовательность с отрицательным шагом

In [167]:
arr_sequence_neg = np.arange(3, -1, -0.4)
print(arr_sequence_neg)

[ 3.   2.6  2.2  1.8  1.4  1.   0.6  0.2 -0.2 -0.6]


С помощью numpy.eye(число) можно создать единичную квадратную матрицу. Аргумент - число строк в квадратной матрице

In [168]:
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Для того, чтобы создать массив, но ничем его не заполнять можно использовать функцию numpy.empty(...). Такое создание будет быстрее, чем создать массив и заполнить его нулями

In [169]:
empty_matrix = np.empty((4, 5))
empty_matrix

array([[7.56587584e-307, 7.56587584e-307, 1.69111725e-306,
        9.34598926e-307, 1.24607192e-306],
       [1.06809792e-306, 2.04720512e-306, 1.69120145e-306,
        8.90103390e-308, 1.95812747e-306],
       [6.23060744e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307],
       [1.86921143e-306, 6.23061763e-307, 6.23053954e-307,
        1.29062025e-306, 1.42410974e-306]])

Также можно узнать форму массива с помощью shape

In [170]:
empty_matrix.shape

(4, 5)

А также тип данных с помощью dtype

In [171]:
empty_matrix.dtype

dtype('float64')

Индексирования и срезы

Для работы только с определенными элементами существуют индексы (номера) элементов. Индекс начинается с 0

In [172]:
arr_test_vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr_test_vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [173]:
arr_test_vector[4]

np.int64(5)

Получаем пятый элемент, который имеет индекс 4

Таким образом можно смотреть сразу на несколько элементов

In [174]:
arr_test_vector[[3, 1]]

array([4, 2])

In [175]:
arr_test_matrix = np.array([[ 1,  2,  3,  4,  5,  6],
                            [ 5,  6,  7,  8,  9,  0], 
                            [ 9, 10, 11, 12, 13, 14],
                            [ 0,  1,  0,  1,  0,  1],
                            [ 9,  8,  7,  6,  5,  4]])
arr_test_matrix

array([[ 1,  2,  3,  4,  5,  6],
       [ 5,  6,  7,  8,  9,  0],
       [ 9, 10, 11, 12, 13, 14],
       [ 0,  1,  0,  1,  0,  1],
       [ 9,  8,  7,  6,  5,  4]])

В двумерном массиве у элемента присутствует два индекса (по строке и по столбцу)

In [176]:
arr_test_matrix[1, 2]

np.int64(7)

Получаем элемент с индексом 1 по строке и с индексом 2 по столбцу

In [177]:
arr_test_matrix[2][3]

np.int64(12)

Получаем элемент с индексом 2 по строке и с индексом 3 по столбцу

Извлечение подмасива с помощью среза

In [178]:
arr_slice_vector = arr_test_vector[3:6]
arr_slice_vector

array([4, 5, 6])

В данном случае новый массив arr_slice_vector берет срез от индекса 3 включительно до индекса 6 не включительно

In [179]:
arr_slice_vector2 = arr_test_vector[:4]
arr_slice_vector2

array([1, 2, 3, 4])

В данном случае новый массив arr_slice_vector2 берет срез от индекса 0 включительно до индекса 4 не включительно

In [180]:
arr_slice_vector3 = arr_test_vector[:-3]
arr_slice_vector3

array([1, 2, 3, 4, 5, 6, 7])

Эта запись означает, что новый массив возьмет срез от индекса 0 включительно до индекса 10-3 = 7 не включительно

In [181]:
arr_slice_vector4 = arr_test_vector[6:]
arr_slice_vector4

array([ 7,  8,  9, 10])

В данном случае новый массив arr_slice_vector4 берет срез от индекса 6 включительно до конца массива

In [182]:
arr_slice_matrix = arr_test_matrix[1:4, 1:3]
arr_slice_matrix

array([[ 6,  7],
       [10, 11],
       [ 1,  0]])

В данном случае извлекается подмассив с помощью среза

Также с помощью операций присваивания можно изменить значение в каком либо срезе

In [183]:
arr_test_identity = np.ones((5, 5))
arr_test_identity

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [184]:
arr_test_identity[1:3, 1:4] = 0
arr_test_identity

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Векторные операции и базовые статистики

In [185]:
source_array = np.arange(8)
source_array

array([0, 1, 2, 3, 4, 5, 6, 7])

Операция возведения в степень поэлементно

In [186]:
exponented_array = source_array ** 2
exponented_array

array([ 0,  1,  4,  9, 16, 25, 36, 49])

Операция сложения массивов

In [187]:
sum_array = source_array + exponented_array
sum_array

array([ 0,  2,  6, 12, 20, 30, 42, 56])

В данном примере происходит сложение элементов в соответствии с индексами, то есть, элемент одного массива с индексом 0 суммируется с элементом другого массива с индексом 0 и далее. Таким образом, получается новый массив

In [188]:
diff_array = source_array - exponented_array
diff_array

array([  0,   0,  -2,  -6, -12, -20, -30, -42])

По тому же пути происходит вычитание одного массива из другого

Абсолютно также работает и операция умножения массивов

In [189]:
mult_array = source_array * exponented_array
mult_array

array([  0,   1,   8,  27,  64, 125, 216, 343])

Для того, чтобы найти среднее значение элемента массива, в NumPy предусмотрен метод mean

In [190]:
np.mean(source_array)

np.float64(3.5)

Для того, чтобы найти сумму всех элементов массива, в NumPy предусмотрен метод sum

In [191]:
np.sum(source_array)

np.int64(28)

Или

In [192]:
source_array.sum()

np.int64(28)

Также можно найти минимальный и максимальный элемент массива

In [193]:
source_array.min()

np.int64(0)

In [194]:
source_array.max()

np.int64(7)

Пример на работу с NumPy

Есть данные о времени подготовки студентов к экзамену (x) и то, сколько баллов они получат (y)

In [195]:
import math

In [196]:
x_i = np.array([2, 4, 6, 8, 10])
y_i = np.array([55, 65, 75, 85, 95])

In [197]:
x_i

array([ 2,  4,  6,  8, 10])

In [198]:
y_i

array([55, 65, 75, 85, 95])

Возьмем средние значения

In [199]:
Xch = np.mean(x_i)
Ych = np.mean(y_i)

In [200]:
Xch

np.float64(6.0)

In [201]:
Ych

np.float64(75.0)

Теперь возьмем выборочные дисперсии

In [202]:
Sx2 = np.sum((x_i - Xch) ** 2) / (len(x_i) - 1)
Sy2 = np.sum((y_i - Ych) ** 2) / (len(y_i) - 1)

In [203]:
Sx2

np.float64(10.0)

In [204]:
Sy2

np.float64(250.0)

Найдем средне квадратичные отклонения

In [205]:
Sx = math.sqrt(Sx2)
Sy = math.sqrt(Sy2)

In [206]:
Sx

3.1622776601683795

In [207]:
Sy

15.811388300841896

Ищем ковариацию, чтобы узнать степень линейной взаимосвязи

In [208]:
cov_xy = np.sum((x_i - Xch) * (y_i - Ych)) / (len(x_i) - 1)
cov_xy

np.float64(50.0)

Коэффициент корелляции Пирсона

In [209]:
r_xy = cov_xy / (Sx * Sy)
r_xy

np.float64(1.0)

Это значит полную положительную линейную связь между временем подготовки и количествомм баллов на экзамене

Чем больше часов подготовки, тем выше баллы на экзамене